# Generated by Django 5.1.5 on 2025-04-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_vendor_remove_product_price_productprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="product_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
