# Generated by Django 5.1.5 on 2025-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_productprice_product_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
