# Generated by Django 5.1.5 on 2025-05-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_remove_productprice_link_productview_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productview",
            old_name="timestamp",
            new_name="viewed_at",
        ),
    ]
