# Generated by Django 5.1.5 on 2025-05-05 12:46

from django.db import migrations, models
import uuid

def generate_unique_order_numbers(apps, schema_editor):
    Order = apps.get_model('myapp', 'Order')
    for order in Order.objects.all():
        order.order_number = f"ORD-{uuid.uuid4().hex[:8].upper()}"
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_orderitem"),
    ]

    operations = [
    migrations.AddField(
        model_name="order",
        name="order_number",
        field=models.CharField(
            blank=True,
            editable=False,
            max_length=20,
            null=True  
        ),
    ),
    migrations.RunPython(generate_unique_order_numbers),
]
