# Generated by Django 5.1.5 on 2025-05-05 12:48

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_order_order_number"),
    ]

    operations = [
    migrations.AlterField(
        model_name="order",
        name="order_number",
        field=models.CharField(
            blank=True,
            editable=False,
            max_length=20,
            null=False,
            unique=True,
        ),
    ),
]
