# Generated by Django 5.1.5 on 2025-05-05 12:51

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                default=myapp.models.generate_order_number,
                editable=False,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
